# Generated by Django 4.2.10 on 2025-03-31 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0003_remove_logo'),
    ]

    operations = [
        # Add fields to SubscriptionPlan model
        migrations.AddField(
            model_name='subscriptionplan',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to Tenant model
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to User model
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to CrmClient model
        migrations.AddField(
            model_name='crmclient',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='crmclient',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crmclient',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to Domain model
        migrations.AddField(
            model_name='domain',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
    ]
