# Generated by Django 4.2.10 on 2025-03-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0004_auto_20250331_1713'),
    ]

    operations = [
        migrations.RunSQL(
            # Rename the table from Django's default naming convention to our custom name
            "ALTER TABLE IF EXISTS ecomm_superadmin_domain RENAME TO ecomm_superadmin_domains;",
            "ALTER TABLE IF EXISTS ecomm_superadmin_domains RENAME TO ecomm_superadmin_domain;"
        ),
    ]
