# Generated by Django 4.2.10 on 2025-04-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_superadmin', '0005_auto_20250331_1741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='ecomm_superadmin_domain',
        ),
    ]
