# Generated by Django 4.2.10 on 2025-03-31 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0002_rename_table_and_column'),
    ]

    operations = [
        # Add fields to TenantUser model
        migrations.AddField(
            model_name='tenantuser',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this user', null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this user', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this user', max_length=255, null=True),
        ),
        
        # Add fields to UserProfile model
        migrations.AddField(
            model_name='userprofile',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to Role model
        migrations.AddField(
            model_name='role',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to Permission model
        migrations.AddField(
            model_name='permission',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to RolePermission model
        migrations.AddField(
            model_name='rolepermission',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to UserRole model
        migrations.AddField(
            model_name='userrole',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to PendingRegistration model
        migrations.AddField(
            model_name='pendingregistration',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to OTP model
        migrations.AddField(
            model_name='otp',
            name='client_id',
            field=models.IntegerField(blank=True, help_text='ID of the client associated with this record', null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
        
        # Add fields to Company model
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.CharField(blank=True, help_text='User who created this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True),
        ),
    ]
