# Generated by Django 4.2.10 on 2025-03-31 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_tenant_admins', '0004_auto_20250331_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time when this record was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated'),
        ),
    ]
